### PR TITLE
Set loader on each page

### PR DESCRIPTION
**Pull request by Abhisheksantra28**
(#43 ) Optimize and Set loader on Home page and also set the same for others pages( please add the labels Gssoc'23) .

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
some conflict in index.html please resolve it .

**Comment by Abhisheksantra28** [comment]
@Anupkjha2601 Sir here I cannot see any conflict .
If there is conflict can you please tell me from where I can solve this . I mean some steps to solve the conflict .

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by Anupkjha2601** [comment]
@Abhisheksantra28 brother , conflict get resolved . So no problem now i am merging it .
thank you for your patience .

**Comment by Abhisheksantra28** [comment]
@Anupkjha2601 Thank you !!

**Pull request merged**
