### PR TITLE
 [Docs] Fix typo in README.md

### LINKED ISSUE #506: [Docs] Fix typo in README.md
I have noticed two typos in the README.md file that need to be corrected:

The first typo is in the word "withing," which should actually be "within."
The second typo is in the word "brokel," which should be "broken."

I would like to work on fixing these typos as part of my contribution to GSSOC23.

image
image

### PR DESCRIPTION
**Pull request by jfmartinz**
This pr fix the typos in `README.md` 

fixes #506 

The first typo is `withing` and changed to `within`
The second typo is `brokel` and changed to `broken`

These changes improve the clarity of the documentation

### CODE REVIEW

**Comment by jfmartinz** [comment]
@Anupkjha2601
@goodchai0

pls check, thank you!

**Comment by jfmartinz** [comment]
@Anupkjha2601
@goodchai0

pls check, thank you!

**Comment by Anupkjha2601** [comment]
@jfmartinz please resolve conflict .

**Comment by jfmartinz** [comment]
> @jfmartinz please resolve conflict .

Resolved. Can you check?

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
