### PR TITLE
Added Recipe page and did the required changes.

### PR DESCRIPTION
**Pull request by hackkbee**
**=================Changed the Name of Tab in Nav bar From To Gallery Recipes====================**
Sinces its a recipe website as I suggested the name is changed from **gallery to recipe.**
image
**===============================Updated the Recipe Cards=============================**
I have updated the cards so that they look pretty and pleasing to the eye and the users will love using them also they are interactive. When you click on the card a popup window appears which displays the recipe for the dish.

image
**================Also Added a popup window which displays Cooking recipe=======================**
This is how the popup window looks like and here the recipe of the dish will be displayed
image

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
@hackkbee your code is good but have some conflict please resolve it.

**Comment by hackkbee** [comment]
> @hackkbee your code is good but have some conflict please resolve it.

Please can you explain the conflicts in detail?
Because I have already the required changes in the mentioned conflicting files

**Comment by hackkbee** [comment]
The conflicts have been already solved please can you recheck

**Comment by Anupkjha2601** [comment]
@hackkbee can you please do it again from staring .

**Comment by Anupkjha2601** [comment]
@hackkbee your code is good and it has level 3 type changes but conflict is not resolving can you please do changes again and then make a pull request as soon as possible .

**Comment by hackkbee** [comment]
Okay I will make the changes

**Comment by Anupkjha2601** [comment]
@hackkbee so sorry but time is over now, they were not counting label after 10 August.

**Pull request closed without merging**
