### PR TITLE
modifiedchanges

### PR DESCRIPTION
**Pull request by 002ayush**
I have made few changes in navigation.Could you please take a look @Anupkjha2601

### CODE REVIEW

**Comment by 002ayush** [comment]
Hey @Anupkjha2601 I have fixed issue #648

**Comment by Anupkjha2601** [comment]
@002ayush please resolve conflict .

**Comment by 002ayush** [comment]
@Anupkjha2601 you can check now it is resolved

**Comment by 002ayush** [comment]
@Anupkjha2601 please merge it

**Comment by 002ayush** [comment]
@Anupkjha2601 can you please merge this.

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
