### PR TITLE
Added `Chatbot`

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @Anupkjha2601 ,
Added `ChatBot` using HTML, CSS & JavaScript it is fully working 👍🏻 

## Video :
[Screencast from 05-06-23 07:43:11 PM IST.webm](https://github.com/Anupkjha2601/food-recipes-website/assets/121503426/537489a4-93a6-401d-8d33-7f64ede3be13)

### It is ready to `Merge` 💯

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Hello @Anupkjha2601 ,
I think you forget to review this.

**Comment by SyedImtiyaz-1** [comment]
Hello @Anupkjha2601 ,
Thank you for assigning me this issue, here is a live working of the chat bot -
## Video -

[Screencast from 25-06-23 06:50:30 PM IST.webm](https://github.com/Anupkjha2601/food-recipes-website/assets/121503426/bc3b5b7d-6052-440e-ac22-0199380df9fa)


### It is ready to *merge* 👍🏻

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by SyedImtiyaz-1** [comment]
@killer2O 
I have fixed that PR already I have removed the old chatbot from there and added different you can review it now going on that website.

**Comment by SyedImtiyaz-1** [comment]
@Anupkjha2601 ,
I think it's just a spammer look at his name my he converted it's goes to ghost but previously it was Killer2O.

& also when I tap on his website it's showing me 404 Page now found.

### Here is the legit proof - 

[Uploading Screencast from 02-07-23 04:55:59 PM IST.webm…]()

**Pull request merged**
