### PR TITLE
Loading screen added

### LINKED ISSUE #331: Loading on landing page
I want to add a loading screen while the landing page is rendering the images the loader will load in the main screen
I want to apply this for this project if needed
@Anupkjha2601 Please let me know if it's important

### PR DESCRIPTION
**Pull request by Soumyajit2825**
I have added a loading animation 
It will load untill the images are rendered

It closes #331 

Please check @goodchai0 @Anupkjha2601

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
@Anupkjha2601 Have you checked it ????

**Comment by Soumyajit2825** [comment]
@Anupkjha2601 Can you please review my PR??
It's coming merge conflicts in some files as you have not yet merged it

**Comment by Soumyajit2825** [comment]
@Anupkjha2601 Have you checked my changes???

**Comment by Soumyajit2825** [comment]
@goodchai0 @Anupkjha2601 I'm waiting to hear from you

**Review by Anupkjha2601 — DISMISSED** [review]

**Comment by Soumyajit2825** [comment]
@Anupkjha2601 I have made this PR last week

**Comment by Soumyajit2825** [comment]
@Anupkjha2601 You have assigned me in this project.
now you're saying that someone else have done it!!!
Seriously!!

**Comment by Anupkjha2601** [comment]
@Soumyajit2825 i am seeing no changes in your pull request , loading pull request already submitted by someone , you can check by clicking the link in about section of repository. that someone has added loading page.

**Comment by Soumyajit2825** [comment]
OK I'm closing it.

**Comment by Anupkjha2601** [comment]
> @Anupkjha2601 You have assigned me in this project. now you're saying that someone else have done it!!! Seriously!!

@Soumyajit2825 brother your file is showing 0 file chenge in file changed section if any change you see in file change you can tell me i will check or merge it .

**Comment by Soumyajit2825** [comment]
@Anupkjha2601 Ya. I've also seen it. I don't know the reason. 😢 In my local machine there is changes and in my forked repo too. But I don't know why it's not showing. Commits are showing but not the files.. 😢 . Maybe some issues from my side.

**Pull request closed without merging**
