### PR TITLE
Updat Readmore button with animation

### PR DESCRIPTION
**Pull request by rohanmittal1163**
hi @Anupkjha2601 @goodchai0 .
i have created an animated readmore button to have a great look
pls review it 
thank you

close -> #205 

#sample
image

### CODE REVIEW

**Comment by rohanmittal1163** [comment]
@goodchai0 pI have created PR for styling button in the github repo pls see to this
thank you

**Comment by rohanmittal1163** [comment]
@goodchai0 pls review it

**Comment by rohanmittal1163** [comment]
hi @Anupkjha2601 @goodchai0 Pls look it to this PR
thank you

**Comment by rohanmittal1163** [comment]
hi @Anupkjha2601 @goodchai0 Pls look it to this PR
thank you

**Comment by Anupkjha2601** [comment]
Hello @rohanmittal1163  sorry for late message your code has some conflict in about.html
css/style.css
index.html
please remove conflict and i make your changes with opening new local file .

**Comment by Anupkjha2601** [comment]
@rohanmittal1163 are you working to resolve the conflict in  about.html
css/style.css
index.html ?

**Comment by rohanmittal1163** [comment]
Yes i am working on it
Today i will complete it

**Pull request closed without merging**
