### PR TITLE
feat: add animations for entire Food Recipes Website 🚀🔥 

### LINKED ISSUE #631: feat: add intro animations to elements for entire food recipes website 🚀✨
## Description
- To enhance the visual appeal and user experience of our Food Recipes Website, we propose adding captivating intro animations to elements as users scroll up or down the pages. 
- The introduction of scroll-triggered animations will add an interactive and engaging touch to the overall browsing experience.

## Key points
1. **Scroll Detection:** Integrate a scroll detection mechanism that identifies users' scroll direction (up or down) and triggers animations accordingly.

2. **Element Selection:** Identify the key elements throughout the website that would benefit from intro animations. This may include recipe cards, images, headings, call-to-action buttons, and other significant components.

3. **Animation Types:** Select appropriate animation types to suit each element. Examples may include fade-ins, slide-ups, slide-downs, zoom-ins, or other subtle effects to create a smooth and polished user experience.

4. **Timing and Delays:** Ensure the animations are timed appropriately to coincide with the appearance of elements on the viewport. Consider implementing delays for animations to maintain a cohesive and visually pleasing flow.

5. **Performance Optimization:** To prevent any impact on website performance, optimize the animations to run smoothly across various devices and browsers. Minimize unnecessary animations to maintain a balance between visual appeal and loading speed.

6. **Accessibility Considerations:** Confirm that the animations do not impede accessibility features and can be easily navigated by users with disabilities or those who prefer reduced motion.

7. **Testing and Feedback:** Conduct thorough testing across different devices and screen sizes to validate the animations' consistency and effectiveness. Gather feedback from users to identify any potential improvements.

## Expected Outcome
- The incorporation of intro animations on scroll will elevate the overall look and feel of our Food Recipes Website. 
- Users will enjoy a delightful browsing experience as they interact with captivating visual elements that gracefully reveal themselves while scrolling. 
- This addition will not only make the website more engaging but also reflect our commitment to delivering an enjoyable and aesthetically pleasing platform for our audience.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Changes proposed
- Added animations for all pages on Food Recipes Website.
- Every animations are smoothly rendered without any issues, and successfully tested.
- I added video which demonstrates examples of animations for some page below.

## Screenshots

https://github.com/Anupkjha2601/food-recipes-website/assets/92252895/dd6a2f9d-a2b2-4eb6-b66a-f8cf69e4fd00

<div align=center>

[ The video can be Laggy due to my low-end Device, The recorder got disturbed that's all.]

</div>

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Animations are added successfully for entire Food Recipes Website @Anupkjha2601 🎉 

Please merge this PR as soon as possible to prevent unwanted conflicts 😄

**Comment by Anupkjha2601** [comment]
@0xabdulkhalid one short conflict come please resolve it .

**Comment by 0xabdulkhalid** [comment]
Done @Anupkjha2601 👍🏻 

Please merge this As soon as possible, otherwise more conflicts will be rised.

**Comment by 0xabdulkhalid** [comment]
Done @Anupkjha2601 👍🏻 

Please merge this As soon as possible, otherwise more conflicts will be rised.

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by 0xabdulkhalid** [comment]
@Anupkjha2601 Please merge this PR now!

**Comment by 0xabdulkhalid** [comment]
@Anupkjha2601 Please merge this PR

**Pull request merged**
