### PR TITLE
contact page revamp

### PR DESCRIPTION
**Pull request by karthiknadar1204**
https://www.awesomescreenshot.com/video/18866482?key=8d5c5535ff024af6ec4345d5c6567bad

@Anupkjha2601 Please review this pr

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
clears #626

**Comment by karthiknadar1204** [comment]
@Anupkjha2601 Please merge this pr as well

**Comment by karthiknadar1204** [comment]
@Anupkjha2601 Please merge this pr

**Comment by karthiknadar1204** [comment]
@Anupkjha2601 Please check this pr, been a while since opened this

**Comment by karthiknadar1204** [comment]
ohk will do and push the changes again @Anupkjha2601

**Comment by Anupkjha2601** [comment]
@karthiknadar1204 your code is running twice , please resolve text written after ==== .

**Pull request closed without merging**
