### PR TITLE
newsletter section modified

### PR DESCRIPTION
**Pull request by chinmayjain08**
this PR solves the issue #320 with a new newsletter section for the website.

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
Hello @chinmayjain08 have some conflict in index.html so please resolve it .

**Comment by chinmayjain08** [comment]
Okay I will resolve them.

**Comment by chinmayjain08** [comment]
@Anupkjha2601 I have resolved all the conflicts and now the PR can be merged.

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by chinmayjain08** [comment]
you have removed level2 label from my new newsletter PR...?
Can you please again put on the level2 tag.
Actually I am a part of GSSOC'23 and the points really matter.
level 1 only provides 10 points.

**Comment by Anupkjha2601** [comment]
You have not  resolved code correctly cause home page showing same thing two times like so that's why I have to revert your code and given level 1.

**Comment by chinmayjain08** [comment]
@Anupkjha2601 but I have created a new newsletter section putting in efforts as well and I look forward to contribute more to the food-recipes-website of yours✨. Also I have had resolved it correctly in my knowledge, maybe something would be missed by me, sorry for that.
I would appreciate if you increase the level of PR as it would provide a boost to my rank.🚀

**Pull request merged**
