### PR TITLE
you  can clearly  able to see Opening timings , address ,  recent posts 

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Before you are  not  able  to  see week days  in opening timings  but now u can   see it clearly   and also  the text .

image

once please  have a look into  this PR  and  merge it  and kindly  inform in case of  any  modifications   .

consider  this  under  GSS0C_23 [contributor]   : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601      once  please check  this  and inform  in case of any modification  : )

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601     once please check this and merge it  consider this under GSS0C_23  contributor  :)

**Comment by Anupkjha2601** [comment]
Hello @Bharath-KumarReddy have some conflict in css/style.css
index.html  so please resolve the conflict .

**Comment by Anupkjha2601** [comment]
@Bharath-KumarReddy conflict didn't resolved.

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601   Once please check I resolved conflicts which I got  : )

**Review by Anupkjha2601 — APPROVED** [review]

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
