### PR TITLE
 Changed the style of search button in galary and a  new feature is added for the  INPUT  field  

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
search button which is clearly visible and when you hover it its color changes and in the input field  when you click on enter then that will log into the console

Before -----

image

After   hovering on search button -----

image

And  after  pressing  enter  in the input  field  
    

              before pressing [ input value ]

image

           
             After pressing enter -----

image

when you pressed on enter then we can see that input value in the console and in the input field will be at initial empty stage.

Please Consider  this  under  GSSOC_23  [contributor]   : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601    Please  look into  this  PR  GSSOC_23 [contributor]   : )

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601     once look into  this  and merge  and please inform  in case of any modifications   GSSOC_23 [contributor]   : )

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601  once Check  this  and  merge  it  and  kindly inform in case of any modifications  GSSOC-23  : )

**Comment by Bharath-KumarReddy** [comment]
@Anupkjha2601  once have a look into this and kindly check and update in case of any modifications then merge it  under GSSOC_23  contributor  : )

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
