### PR TITLE
Adds contributing.md file

### PR DESCRIPTION
**Pull request by rohanmittal1163**
hey @Anupkjha2601 @goodchai0 
I have created the licesnse for your github repo
pls do have a look 

solves #206 

thank you

### CODE REVIEW

**Comment by rohanmittal1163** [comment]
hi @Anupkjha2601 @goodchai0 
pls review this.
i have created contributing.md file for your github repo
thank you

**Comment by rohanmittal1163** [comment]
hi @Anupkjha2601 @goodchai0
pls review this.
i have created contributing.md file for your github repo
thank you

**Comment by rohanmittal1163** [comment]
hi @Anupkjha2601 @goodchai0
pls review this.
i have created contributing.md file for your github repo
thank you

**Review by goodchai0 — DISMISSED** [review]

**Review by goodchai0 — APPROVED** [review]

**Comment by rohanmittal1163** [comment]
@goodchai0 @Anupkjha2601 is there any problem with my PR request.
I can change with your requirement you want to add

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
