### PR TITLE
made the website fine

### PR DESCRIPTION
**Pull request by bhavyanarnoli**
https://drive.google.com/file/d/1nis7cE4o5I0s2OzTyxtVi40JM6U-OoJT made the req changess see here

### CODE REVIEW

**Comment by bhavyanarnoli** [comment]
https://github.com/Anupkjha2601/food-recipes-website/assets/108413315/eb1900da-ff36-43ba-8a24-57b8de83ca1f

lot of issues in code fixed them

**Comment by bhavyanarnoli** [comment]
@Anupkjha2601  pls review

**Comment by bhavyanarnoli** [comment]
done under gssoc

**Comment by bhavyanarnoli** [comment]
#409

**Comment by Anupkjha2601** [comment]
@bhavyanarnoli have some conflict in index.html  your code have two scroll button so please remove orange one from index.html and also some changes in testimonial section so please again clone new file then do changes .

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by Anupkjha2601** [comment]
@bhavyanarnoli your this pull request causing some problem in website index section like footer is coming two times , and testimonial section is coming after footer so please make changes in new pull request . i have seen that your code made changes in testimonial section as well as in chatbot but index.html page not working perfectly so make changes in new pull request.

**Comment by bhavyanarnoli** [comment]
okkkaa

**Comment by bhavyanarnoli** [comment]
will do in a week or so ig?

**Comment by Anupkjha2601** [comment]
Ok you can make pull request any time I have assigned you no problem.

**Comment by bhavyanarnoli** [comment]
yes ill do it in a week

**Pull request merged**
