### PR TITLE
added functionality to the scroll to bottom button 

### PR DESCRIPTION
**Pull request by ch-sohan**
I have added functionality to the scroll down button. (#34)

 When the scroll down button is clicked, it now scrolls the page to the "Today's Special" section.

image

image

### CODE REVIEW

**Comment by ch-sohan** [comment]
Hi @goodchai0 , @Anupkjha2601 can you please review this pull request. 
Issue : #34

**Review by goodchai0 — DISMISSED** [review]

**Comment by Anupkjha2601** [comment]
@have some conflict in index.html and your site has older scroll button so you can add newer scroll button which is there in site link   https://anupkjha2601.github.io/food-recipes-website/index.html  so you can add its scrool button.

**Comment by ch-sohan** [comment]
@Anupkjha2601 The website has the same button as of my site
Sorry for the inconvenience caused . I'll work on the issue

image

**Comment by Anupkjha2601** [comment]
@ch-sohan bro conlict didn't resolved.

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
