### PR TITLE
refactor: revamp the design of google translator button for all pages 🪄✨ 

### LINKED ISSUE #685: feat: revamp the design of select languages button on header 💫✨
## Description
- The current state of `Select Languages` Button lacks styles, So it doesn't look good for users.
- We must need to revamp the design in order to match the site's theme with as best looking button component.
- This helps to improve the User Interface and the User Experience too.

## Screenshot (current state)
image

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Changes proposed
- Revamped the Google Translator button component's styling into styling of Buttons like on Header.

## Screenshots
|BEFORE|AFTER|
|:---:|:----:|
|image|image|

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@Anupkjha2601 Your review is appreciated 🙌🏻

**Comment by Anupkjha2601** [comment]
@0xabdulkhalid have some conflict in icons section please resolve it.

**Comment by 0xabdulkhalid** [comment]
### Conflicts are resolved @Anupkjha2601 🎉

**Comment by 0xabdulkhalid** [comment]
### Conflicts are resolved @Anupkjha2601 🎉

**Review by Anupkjha2601 — APPROVED** [review]

**Pull request merged**
