### PR TITLE
Fixed Alignment `Major issue`

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @Anupkjha2601 ,
## Issue No. #398 

The structure of website is fixed 💯 
### Video -
[Screencast from 25-06-23 08:57:34 PM IST.webm](https://github.com/Anupkjha2601/food-recipes-website/assets/121503426/710d2157-6545-4e42-a71e-f74bfed56ac5)

### It is ready to merge 👍🏻

### CODE REVIEW

**Review by Anupkjha2601 — COMMENTED** [review]
instagram bug already resolve so remove it.

**Comment by Anupkjha2601** [comment]
@SyedImtiyaz-1 have some conflict in css/style.css
index.html
please resolve it.

**Comment by SyedImtiyaz-1** [comment]
@Anupkjha2601 ,
Conflict Resolved

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by Anupkjha2601** [comment]
@SyedImtiyaz-1 are you copying from anywhere you have deleted index.html.

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 are you copying from anywhere you have deleted index.html.

No it's a branch of insta icon which you said to remove I just removed that file nothing else. 
You can check your website it's fully working now.

**Comment by Anupkjha2601** [comment]
after revert it is working bhai

**Comment by SyedImtiyaz-1** [comment]
@Anupkjha2601 but there is still a bug of chatbot check the PR #402 

## Issue -
Screenshot from 2023-06-25 23-55-18

**Comment by SyedImtiyaz-1** [comment]
## I think you already merged it. Thank you!

**Pull request merged**
