### PR TITLE
animations added to the website {video added}

### PR DESCRIPTION
**Pull request by harshita-2003**
+animation added making it more attractive
+another animation todays special

*video*

https://github.com/Anupkjha2601/food-recipes-website/assets/119532943/e4819c4d-6f14-4cdb-ab10-9b5a7d5da4c2

### CODE REVIEW

**Comment by harshita-2003** [comment]
@Anupkjha2601 do acknowledge and merge the request it got conflicts earlier

**Comment by Anupkjha2601** [comment]
@harshita-2003 your contribution is good if you want to merge pull request you have to resolve conflict .

**Comment by harshita-2003** [comment]
@Anupkjha2601 conflicts resolved !! Kindly merge the PR.

**Comment by harshita-2003** [comment]
@Anupkjha2601  kindly merge the PR ,conflicts are resolved as mentioned

**Pull request closed without merging**
