### PR TITLE
fixed the scroll to top button

### PR DESCRIPTION
**Pull request by Illaf**
close issue #451 
I have fixed the scroll to top button which initially was not showing the arrow button. I have instead added a new scroll to  top button because the previous one was having issues with z-index because the website components have been given proper z indices. Nevertheless, it works the same.
If you want any changes then please inform me
Thank you for having me as a contributor

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
@Illaf please resolve conflict.

**Comment by Illaf** [comment]
> @Illaf please resolve conflict.

Done!👍

**Comment by Anupkjha2601** [comment]
@Illaf please resolve conflict correctly and fast now only ten days left.

**Comment by Illaf** [comment]
@Anupkjha2601 resolved .Please check now and tell if any further problems are there

**Pull request merged**
