### PR TITLE
Adds a License file

### PR DESCRIPTION
**Pull request by rohanmittal1163**
hi @goodchai0 
I have added license file. pls review it and inform me if there is any change.
thank you

### CODE REVIEW

**Comment by rohanmittal1163** [comment]
@Anupkjha2601 @goodchai0 pls review the license file.
thank you

**Comment by rohanmittal1163** [comment]
hey @Anupkjha2601 @goodchai0 
I have created the licesnse for your github repo
pls do have a look 

solves #207 

thank you

**Comment by rohanmittal1163** [comment]
hey @Anupkjha2601 @goodchai0

pls merge this branch under GSSOC'23

solves https://github.com/Anupkjha2601/food-recipes-website/issues/207

thank you

**Comment by rohanmittal1163** [comment]
hey @Anupkjha2601 @goodchai0

pls merge this branch under GSSOC'23

solves https://github.com/Anupkjha2601/food-recipes-website/issues/207

thank you

**Comment by Anupkjha2601** [comment]
@rohanmittal1163 pleade resolve the conflict.

**Comment by rohanmittal1163** [comment]
ok i'll do it today itself 
sorry for the delay

**Pull request closed without merging**
