### PR TITLE
`Mail` link in `footer` is now clickable

### LINKED ISSUE #134: Bug in the `Footer`
Hello @Anupkjha2601,

I found a bug regarding the footer is that the Our Address section is not properly showing the accurate text and mail is also not clickable so I like to fix this please assign me this issue.

## Bug Screenshot - 
image

### Soon will raise a `PR`

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @Anupkjha2601,
I have fixed the issue which is in the footer in every page of the website.

## Video -
[Screencast from 24-05-23 06:04:43 PM IST.webm](https://github.com/Anupkjha2601/food-recipes-website/assets/121503426/56c7f8da-dda3-4c89-bb05-878d1180a3f4)

## It is ready to `merge` 👍🏻

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
Hello 
[SyedImtiyaz-1](https://github.com/SyedImtiyaz-1) there is one conflict in index.html please resolve it then  i merge it .

**Comment by SyedImtiyaz-1** [comment]
Hello @Anupkjha2601,
## Conflicts resolved !

**Comment by Anupkjha2601** [comment]
Hello [SyedImtiyaz-1](https://github.com/SyedImtiyaz-1) brother conflict is not resolved . please check the problem again.

**Comment by SyedImtiyaz-1** [comment]
@Anupkjha2601 Issues resolved

**Pull request merged**
