### PR TITLE
First Contribution

### PR DESCRIPTION
**Pull request by SpandanM110**
Changes Done on Services Page:
1) Footer Spacing
2) Text placing in an proper arrangement
3) Image Icon introduction

### CODE REVIEW

**Comment by SpandanM110** [comment]
All types of updates has been done!

**Comment by SpandanM110** [comment]
I am Spandan | Contributor of GSSOC'23

**Comment by SpandanM110** [comment]
@Anupkjha2601 please have a look to the changes

**Comment by Anupkjha2601** [comment]
have some conflict in about.html
gallery.html
index.html
services.html
  please resolve it.

**Pull request closed without merging**
