### PR TITLE
contributor section is not showing

### PR DESCRIPTION
**Pull request by SubhamB2003**
@Anupkjha2601Can you please merge my pr

## Fixes Issue
solves #769

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
@SubhamB2003 please resolve conflict.

**Comment by SubhamB2003** [comment]
Please check

**Comment by SubhamB2003** [comment]
@Anupkjha2601 Please merge my pr.

**Comment by SubhamB2003** [comment]
@Anupkjha2601 Hey, I thing you forgot to add labels

**Pull request merged**
